services:
  webserver:
    build:
      target: server__caddy--dev
    ports:
      - "8080:8080"
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - ./public:/app/public:ro

  backend:
    build:
      target: backend__php--dev
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=streetfighter6replays-back
    volumes:
      - .:/app

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
###< symfony/mailer ###
